name: Main App
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: iad
  pscale_base_directory: .pscale

jobs:
  merge-deployment-request:
    name: "Merge - click here"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: create and merge deployment request
        timeout-minutes: 10
        env:
          GITHUB_USER: ${{github.actor}}
          PLANETSCALE_SERVICE_TOKEN_ID: ${{secrets.PLANETSCALE_SERVICE_TOKEN_ID}}
          PLANETSCALE_SERVICE_TOKEN: ${{secrets.PLANETSCALE_SERVICE_TOKEN}}
          DB_NAME: ${{secrets.DB_NAME}}
          BRANCH_NAME: "placeholder"
          ORG_NAME: ${{secrets.ORG_NAME}}
        working-directory: ${{env.pscale_base_directory}}/cli-helper-scripts/
        run: ./create-and-merge-deployment-request.sh
